<a href="https://colab.research.google.com/github/blessey15/Pytorch-Self-Projects/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Basics

Basic Tutorials

In [ ]:
import torch 
import numpy as np
import pandas as pd

In [ ]:
t1=torch.tensor(4.0)
t1.dtype

torch.float32

In [ ]:
t2=torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [ ]:
t3=torch.tensor([[1.,2],[3,4]])
t3

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
t3.shape

torch.Size([2, 2])

In [ ]:
v=torch.tensor(3.0)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [ ]:
y=w*v+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
#compute derivative
y.backward()
print('dy/dv',v.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dv None
dy/dw tensor(3.)
dy/db tensor(1.)


In [ ]:
x=np.array([[1,2],[3,4]])

In [ ]:
#converting numpy array into tensor
Y=torch.from_numpy(x)
Y

tensor([[1, 2],
        [3, 4]])

In [ ]:
# converting a torch tensor into numpy
z=Y.numpy()
z

array([[1, 2],
       [3, 4]])

#Gradient Descent

In [ ]:
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')

In [ ]:
targets=np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [ ]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)

In [ ]:
def model(x):
  return x@w.t()+b

# "@"-matrix multiplication in python
# "x.t()" - transpose of x  

In [ ]:
def mse(t1,t2):
  diff=t1-t2
  MSE=torch.sum(diff*diff)/diff.numel()
  return MSE

# 'nume1 - returns the no. of elements in the tensor
# '*' - element wise multiplication in pytorch 

In [ ]:
#training for 100 epochs by adjusting weights and reset gradient_
for i in range(150):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
preds

tensor([[ 61.3007,  73.1992],
        [ 73.1148,  85.1860],
        [132.7203, 163.5305],
        [ 44.6719,  51.2779],
        [ 72.1843,  84.0352]], grad_fn=<AddBackward0>)

Linear Regression using built-in Functions

In [ ]:
from sklearn.datasets import load_boston
data=load_boston()
data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [ ]:
df=pd.DataFrame(data.data)
df.columns=data.feature_names
df['price']=data.target

In [ ]:
df.describe()

CRIM          ZN       INDUS  ...           B       LSTAT       price
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...  356.674032   12.653063   22.532806
std      8.601545   23.322453    6.860353  ...   91.294864    7.141062    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377500    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440000   11.360000   21.200000
75%      3.677083   12.500000   18.100000  ...  396.225000   16.955000   25.000000
max     88.976200  100.000000   27.740000  ...  396.900000   37.970000   50.000000

[8 rows x 14 columns]

In [ ]:
dataset=df[df.columns[:-1]]

In [ ]:
dataset = df[df.columns[:-1]]
dataset = dataset.apply(
    lambda x: (x - x.mean()) / x.std()
)

dataset['price'] = df.price

In [ ]:
Y = dataset['price'].to_numpy()
X=dataset.drop('price',axis=1).to_numpy()


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(404, 13) (102, 13) (404,) (102,)


In [ ]:
X_train=torch.tensor(X_train,dtype=torch.float32)
X_test=torch.tensor(X_test,dtype=torch.float32)
y_train=torch.tensor(y_train,dtype=torch.float32)
y_test=torch.tensor(y_test,dtype=torch.float32)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [ ]:
from torch.utils.data import TensorDataset
train_ds=TensorDataset(X_train,y_train)

In [ ]:
from torch.utils.data import DataLoader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [ ]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[-0.4141, -0.4872, -0.9689, -0.2723, -0.9121, -0.3838, -0.8340,  0.3002,
         -0.7522, -0.9567,  0.0205,  0.4306,  0.0290],
        [-0.2640, -0.4872,  1.2307, -0.2723,  0.4341, -0.3112,  1.1164, -0.9677,
         -0.5225, -0.0311, -1.7347, -0.0305, -0.8714],
        [ 0.6859, -0.4872,  1.0150, -0.2723,  1.3661,  0.6310,  0.9068, -0.6169,
          1.6596,  1.5294,  0.8058, -3.8337,  0.8482],
        [-0.3956,  0.3703, -1.1380, -0.2723, -0.9648,  0.7506, -1.2922,  0.1452,
         -0.5225, -1.1406, -1.6423,  0.4406, -1.0927],
        [-0.4137,  0.9277, -1.3056, -0.2723, -0.7136,  1.3540, -0.9761,  0.1078,
         -0.2928, -1.1050, -0.0257,  0.4053, -0.8014]])
tensor([22.5000, 24.3000, 14.9000, 35.1000, 36.1000])


In [ ]:
#define a model
w_num = X_train.shape[1]
model = torch.nn.Sequential(
    torch.nn.Linear(w_num, 1)
)

torch.nn.init.normal_(model[0].weight, mean=0, std=0.1)
torch.nn.init.constant_(model[0].bias, val=0)


Parameter containing:
tensor([0.], requires_grad=True)

In [ ]:
#loss function
loss=torch.nn.MSELoss()

In [ ]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.05)

In [ ]:
#train
def fit(num_epochs,model,loss_fn,opt):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      l=loss(pred,yb)
      l.backward()
      opt.step() #update parameters using gradients
      opt.zero_grad()
    if(epoch+1)%10==0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1,num_epochs,l.item()))


In [ ]:
fit(100,model,loss,optimizer)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:445: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:445: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch [10/100], Loss: 23.2134
Epoch [20/100], Loss: 55.2848
Epoch [30/100], Loss: 228.6105
Epoch [40/100], Loss: 96.9392
Epoch [50/100], Loss: 240.7349
Epoch [60/100], Loss: 78.1616
Epoch [70/100], Loss: 271.2132
Epoch [80/100], Loss: 29.2677
Epoch [90/100], Loss: 34.2189
Epoch [100/100], Loss: 53.7367


In [ ]:
print(loss(model(X_test), y_test).item())

89.64643096923828


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:445: UserWarning: Using a target size (torch.Size([102])) that is different to the input size (torch.Size([102, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
